name: Run Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Display Chrome version
      run: chrome --version

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: '3.9.4'

    - name: Build and run tests
      run: mvn clean test

    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: extent-report
        path: test-output/extent-report.html
