name: Trigger Selenium Tests in Repo B

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_B_TOKEN }}" \
            https://api.github.com/repos/<YOUR_USERNAME_OR_ORG>/repo-b-name/dispatches \
            -d '{"event_type":"run-selenium-tests"}'
